
import java.util.ArrayList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author maier
 */
public class FenetreQuiz extends javax.swing.JFrame {  
   private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FenetreQuiz.class.getName());
    private ArrayList<Question> listeQuestions;
    private int indexQuestionCourante = 0;
    private int score = 0;
    private int scoreValue =0;
    
    
    /**
     * Creates new form FenetreQuiz
     */
    public FenetreQuiz() {
        initComponents();
        listeQuestions = new ArrayList<>();
        indexQuestionCourante = 0;
        score = 0;
       initialiserQuestion();
       afficherQuestionCourante();   
    }
    
   private void verifierReponse(int choixUtilisateur) {

    Question q = listeQuestions.get(indexQuestionCourante);

    if (choixUtilisateur == q.getIndexBonneReponse()) {
        score++;
        Score.setText("Score : " + score);
        feedback.setText("Bonne réponse !");
    } else {
        feedback.setText("Mauvaise réponse ! La bonne réponse était : " 
                + q.getIndexBonneReponse());
    }

    // Désactiver les boutons
    btnRep1.setEnabled(false);
    btnRep2.setEnabled(false);
    btnRep3.setEnabled(false);
    btnRep4.setEnabled(false);
}
   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblQuestion = new javax.swing.JLabel();
        btnRep1 = new javax.swing.JButton();
        feedback = new javax.swing.JLabel();
        Score = new javax.swing.JLabel();
        btnRep2 = new javax.swing.JButton();
        btnRep3 = new javax.swing.JButton();
        btnRep4 = new javax.swing.JButton();
        QuestionSuivante = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblQuestion.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblQuestion.setForeground(new java.awt.Color(51, 0, 255));
        lblQuestion.setText("Question");
        lblQuestion.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        btnRep1.setText("jButton1");
        btnRep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep1ActionPerformed(evt);
            }
        });

        feedback.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        feedback.setText("jLabel1");

        Score.setText("Score");

        btnRep2.setText("jButton1");
        btnRep2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep2ActionPerformed(evt);
            }
        });

        btnRep3.setText("jButton1");
        btnRep3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep3ActionPerformed(evt);
            }
        });

        btnRep4.setText("jButton1");
        btnRep4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep4ActionPerformed(evt);
            }
        });

        QuestionSuivante.setText("Question Suivante");
        QuestionSuivante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuestionSuivanteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(btnRep1)
                                .addGap(76, 76, 76)
                                .addComponent(btnRep2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81)
                                .addComponent(btnRep3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addComponent(btnRep4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Score, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(feedback, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(QuestionSuivante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(Score))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lblQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRep3)
                    .addComponent(btnRep1)
                    .addComponent(btnRep2)
                    .addComponent(btnRep4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(feedback, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(QuestionSuivante, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRep1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep1ActionPerformed
        verifierReponse(1);
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnRep1ActionPerformed

    private void btnRep2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep2ActionPerformed
         verifierReponse(2);
// TODO add your handling code here:
    }//GEN-LAST:event_btnRep2ActionPerformed

    private void btnRep3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep3ActionPerformed
         verifierReponse(3);
// TODO add your handling code here:
    }//GEN-LAST:event_btnRep3ActionPerformed

    private void btnRep4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep4ActionPerformed
         verifierReponse(4);
// TODO add your handling code here:
    }//GEN-LAST:event_btnRep4ActionPerformed

    private void QuestionSuivanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuestionSuivanteActionPerformed
        indexQuestionCourante++;

        if (indexQuestionCourante < listeQuestions.size()) {
            afficherQuestionCourante();
        } else {
            // PLUS AUCUNE QUESTION → fin du quiz
            lblQuestion.setText("<html><h3>Quiz terminé !</h3><br>Score final : "
                    + score + " / " + listeQuestions.size() + "</html>");

            // Désactiver les boutons
            btnRep1.setEnabled(false);
            btnRep2.setEnabled(false);
            btnRep3.setEnabled(false);
            btnRep4.setEnabled(false);

            // Désactiver le bouton Question suivante
            QuestionSuivante.setEnabled(false);

            // Facultatif : Effacer réponse correcte
            feedback.setText("");
        }
// TODO add your handling code here:
    }//GEN-LAST:event_QuestionSuivanteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FenetreQuiz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton QuestionSuivante;
    private javax.swing.JLabel Score;
    private javax.swing.JButton btnRep1;
    private javax.swing.JButton btnRep2;
    private javax.swing.JButton btnRep3;
    private javax.swing.JButton btnRep4;
    private javax.swing.JLabel feedback;
    private javax.swing.JLabel lblQuestion;
    // End of variables declaration//GEN-END:variables

    private void initialiserQuestion() {
        listeQuestions.add(new Question (
            "Quel est le mot-clé pour créer une classe en Java ?",
            "class",
            "Class",
            "classe",
            "object",
            1
        ));
        listeQuestions.add(new Question (
            "Quel type de données est utilisé pour stocker un nombre entier en Java ?",
            "float",
            "int",
            "String",
            "boolean",
            2
        ));
        listeQuestions.add(new Question (
            "Quel modificateur d'accès rend un attribut accessible uniquement dans sa classe ?",
            "public",
            "protected",
            "private",
            "default",
            3
        ));
        listeQuestions.add(new Question(
            "Quelle classe permet de créer une liste dynamique en Java ?",
            "Array",
            "LinkedList",
            "ArrayList",
            "Vector",
            3
        ));
        listeQuestions.add(new Question(
            "Quel composant Swing permet d'afficher du texte non modifiable ?",
            "JTextField",
            "JButton",
            "JLabel",
            "JTextArea",
            3
        ));
                
    }

    private void afficherQuestionCourante() {
        Question QuestionA = listeQuestions.get(indexQuestionCourante);
        lblQuestion.setText(QuestionA.getIntitule());
        btnRep1.setText(QuestionA.getProposition1());
        btnRep2.setText(QuestionA.getProposition2());
        btnRep3.setText(QuestionA.getProposition3());
        btnRep4.setText(QuestionA.getProposition4());
        
        btnRep1.setEnabled(true);
        btnRep2.setEnabled(true);
        btnRep3.setEnabled(true);
        btnRep4.setEnabled(true);
        
        
        
        
        
        
        
                
    }

   
}
